import { Route, GitCompareArrows, Compass, BrainCircuit, Network, Star } from 'lucide-react';
const key=([r,c])=>`${r},${c}`; const fromKey=k=>k.split(',').map(Number); const dirs=[[1,0],[-1,0],[0,1],[0,-1]];
function neighbors(maze,[r,c]){return dirs.map(([a,b])=>[r+a,c+b]).filter(([x,y])=>x>=0&&y>=0&&x<maze.length&&y<maze.length&&!maze[x][y])}
function reconstruct(parent,start,goal){const out=[];let cur=goal;while(key(cur)!==key(start)){out.push(cur);cur=parent.get(key(cur));if(!cur)return []}return out.reverse()}
function result(visited,parent,start,goal,t0){const path=reconstruct(parent,start,goal);return {visitedOrder:visited.filter(n=>key(n)!==key(start)&&key(n)!==key(goal)),path,nodesExplored:visited.length, pathLength:path.length,executionTime:performance.now()-t0,success:path.length>0}}
export function bfs(maze,start,goal){const t=performance.now(),q=[start],seen=new Set([key(start)]),parent=new Map,visited=[];for(let i=0;i<q.length;i++){const n=q[i];visited.push(n);if(key(n)===key(goal))break;for(const x of neighbors(maze,n))if(!seen.has(key(x))){seen.add(key(x));parent.set(key(x),n);q.push(x)}}return result(visited,parent,start,goal,t)}
export function dfs(maze,start,goal){const t=performance.now(),stack=[start],seen=new Set,parent=new Map,visited=[];while(stack.length){const n=stack.pop();if(seen.has(key(n)))continue;seen.add(key(n));visited.push(n);if(key(n)===key(goal))break;for(const x of neighbors(maze,n).reverse())if(!seen.has(key(x))){parent.set(key(x),n);stack.push(x)}}return result(visited,parent,start,goal,t)}
export function dijkstra(maze,start,goal){const t=performance.now(),q=[[0,start]],dist=new Map([[key(start),0]]),parent=new Map,visited=[];while(q.length){q.sort((a,b)=>a[0]-b[0]);const [d,n]=q.shift();if(d!==dist.get(key(n)))continue;visited.push(n);if(key(n)===key(goal))break;for(const x of neighbors(maze,n)){const nd=d+1;if(nd<(dist.get(key(x))??Infinity)){dist.set(key(x),nd);parent.set(key(x),n);q.push([nd,x])}}}return result(visited,parent,start,goal,t)}
const heuristic=(a,b,type)=>type==='Euclidean'?Math.hypot(a[0]-b[0],a[1]-b[1]):Math.abs(a[0]-b[0])+Math.abs(a[1]-b[1]);
export function astar(maze,start,goal,type='Manhattan'){const t=performance.now(),q=[[0,0,start]],g=new Map([[key(start),0]]),parent=new Map,visited=[];while(q.length){q.sort((a,b)=>a[0]-b[0]);const [,cost,n]=q.shift();if(cost!==g.get(key(n)))continue;visited.push(n);if(key(n)===key(goal))break;for(const x of neighbors(maze,n)){const ng=cost+1;if(ng<(g.get(key(x))??Infinity)){g.set(key(x),ng);parent.set(key(x),n);q.push([ng+heuristic(x,goal,type),ng,x])}}}return result(visited,parent,start,goal,t)}
export function greedy(maze,start,goal,type='Manhattan'){const t=performance.now(),q=[[heuristic(start,goal,type),start]],seen=new Set([key(start)]),parent=new Map,visited=[];while(q.length){q.sort((a,b)=>a[0]-b[0]);const [,n]=q.shift();visited.push(n);if(key(n)===key(goal))break;for(const x of neighbors(maze,n))if(!seen.has(key(x))){seen.add(key(x));parent.set(key(x),n);q.push([heuristic(x,goal,type),x])}}return result(visited,parent,start,goal,t)}
export function bidirectional(maze,start,goal){const t=performance.now(),qa=[start],qb=[goal],sa=new Set([key(start)]),sb=new Set([key(goal)]),pa=new Map,pb=new Map,visited=[];let meet=null;while(qa.length&&qb.length&&!meet){for(const [q,own,other,parent] of [[qa,sa,sb,pa],[qb,sb,sa,pb]]){const n=q.shift();visited.push(n);for(const x of neighbors(maze,n)){if(own.has(key(x)))continue;own.add(key(x));parent.set(key(x),n);q.push(x);if(other.has(key(x))){meet=x;break}}if(meet)break}}if(!meet)return {visitedOrder:visited,path:[],nodesExplored:visited.length,pathLength:0,executionTime:performance.now()-t,success:false};const left=reconstruct(pa,start,meet);const right=[];let cur=meet;while(key(cur)!==key(goal)){cur=pb.get(key(cur));if(!cur)break;right.push(cur)}const path=[...left,...right];return {visitedOrder:visited,path,nodesExplored:visited.length,pathLength:path.length,executionTime:performance.now()-t,success:true}}
export const algorithmList=[{id:'bfs',name:'BFS',short:'BFS',description:'Breadth-First Search',Icon:Network},{id:'dfs',name:'DFS',short:'DFS',description:'Depth-First Search',Icon:GitCompareArrows},{id:'dijkstra',name:'Dijkstra',short:'Dijkstra',description:'Uniform Cost Search',Icon:Route},{id:'astar',name:'A* Search',short:'A*',description:'Heuristic Search',Icon:Star},{id:'greedy',name:'Greedy Best-First',short:'Greedy',description:'Heuristic Driven',Icon:Compass},{id:'bidirectional',name:'Bidirectional',short:'Bidirectional',description:'Meet in the Middle',Icon:BrainCircuit}];
export const solvers={bfs,dfs,dijkstra,astar,greedy,bidirectional};
